import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Brain, Upload, Zap, Trophy, BookOpen, Globe } from "lucide-react";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import robotMascot from "@/assets/robot-mascot.png";

const features = [
  { icon: Upload, title: "Upload Anything", desc: "PDFs, images, or plain text — we handle it all." },
  { icon: Brain, title: "AI-Powered", desc: "Smart questions generated by advanced AI models." },
  { icon: Zap, title: "Instant Quizzes", desc: "Get your quiz in seconds, not minutes." },
  { icon: Trophy, title: "Track Progress", desc: "See your scores, streaks, and improvement over time." },
  { icon: BookOpen, title: "Multiple Types", desc: "MCQ, True/False, Short Answer, or Mixed." },
  { icon: Globe, title: "Any Language", desc: "Generate quizzes in your preferred language." },
];

const testimonials = [
  { name: "Sarah K.", text: "QuizBot AI helped me ace my finals! The quizzes are spot-on.", avatar: "🧑‍🎓" },
  { name: "Mike R.", text: "I use it to prep training materials for my team. Huge time saver!", avatar: "👨‍💼" },
  { name: "Priya S.", text: "Love the robot theme — makes studying actually fun!", avatar: "👩‍💻" },
];

const Landing = () => (
  <div className="min-h-screen">
    <Navbar />

    {/* Hero */}
    <section className="pt-28 pb-20 px-4">
      <div className="container mx-auto flex flex-col md:flex-row items-center gap-12">
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6 }}
          className="flex-1 text-center md:text-left"
        >
          <h1 className="font-heading text-4xl md:text-6xl font-bold leading-tight mb-6">
            Meet <span className="text-gradient">QuizBot AI</span> 🤖
          </h1>
          <p className="text-lg text-muted-foreground mb-8 max-w-lg">
            Upload your notes, PDFs, or images and let our AI generate personalized quizzes instantly. Study smarter, score higher!
          </p>
          <Link to="/signup">
            <Button size="lg" className="gradient-primary text-primary-foreground text-lg px-8 py-6 rounded-full shadow-soft hover:shadow-hover transition-shadow">
              Get Started Free ✨
            </Button>
          </Link>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="flex-1 flex justify-center"
        >
          <img
            src={robotMascot}
            alt="QuizBot AI Robot Mascot"
            width={400}
            height={400}
            className="animate-float drop-shadow-2xl"
          />
        </motion.div>
      </div>
    </section>

    {/* Features */}
    <section id="features" className="py-20 px-4 bg-muted/50">
      <div className="container mx-auto">
        <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-4">Why QuizBot AI? 🚀</h2>
        <p className="text-center text-muted-foreground mb-12 max-w-md mx-auto">Everything you need to supercharge your study sessions.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="bg-card rounded-2xl p-6 shadow-card hover:shadow-hover transition-shadow border border-border"
            >
              <div className="w-12 h-12 rounded-xl gradient-primary flex items-center justify-center mb-4">
                <f.icon className="text-primary-foreground" size={24} />
              </div>
              <h3 className="font-heading font-semibold text-lg mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>

    {/* Testimonials */}
    <section id="testimonials" className="py-20 px-4">
      <div className="container mx-auto">
        <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-12">Loved by Students & Pros 💜</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((t, i) => (
            <motion.div
              key={t.name}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="bg-card rounded-2xl p-6 shadow-card border border-border"
            >
              <p className="text-muted-foreground mb-4">"{t.text}"</p>
              <div className="flex items-center gap-3">
                <span className="text-3xl">{t.avatar}</span>
                <span className="font-semibold">{t.name}</span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>

    <Footer />
  </div>
);

export default Landing;
